name: Zip Azure Storage Dotnet Files
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'allfiles/labs/dotnet/azure-storage/**'

defaults:
  run:
    shell: pwsh

jobs:
  create_zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Azure Storage zip
      run: | 
        cd ./allfiles/labs/dotnet/azure-storage
        zip -r -q ../../../downloads/dotnet/azure-storage-dotnet.zip *
    - name: Commit and push
      uses: Endbug/add-and-commit@v7
      with:
        add: 'allfiles/downloads/dotnet/azure-storage-dotnet.zip'
        message: 'Updating Zip for dotnet source files'
        push: true

